config/routes.rb
Rails.application.routes.draw do

  resources :policies

  mount RedactorRails::Engine => '/redactor_rails'
  get "/comments/new/(:parent_id)", to: "comments#new", as: :new_comment
  post "/comments/new/(:parent_id)", to: "comments#create", as: :create_nested_comment

  resources :searches, except: [:index, :destroy, :edit, :update]

  resources :categories do
    resources :posts do
      member do
        post "like", to: "posts#like", as: :like
        post "unlike", to: "posts#unlike", as: :unlike
        # get ":slug", to: "posts#show", as: :show
        # get ":slug/edit", to: "posts#edit"
        # delete ":slug", to: "posts#destroy"
        # patch ":slug", to: "posts#update"
        # get ":slug/comments", to: "comments#index", as: :post_comments
        post "comments", to: "comments#create", as: :comments_create
        delete "comments/:id", to: "comments#destroy", as: :comment_destroy
        get "comments/:id/edit", to: "comments#edit", as: :comment_edit
        patch "comments/:id", to: "comments#update", as: :comment
        put "comments/:id", to: "comments#update", as: :comment_update
        post "comments/like", to: "comments#like", as: :comment_like
        post "comments/unlike", to: "comments#unlike", as: :comment_unlike
        # get ":slug/comments/:id", to: "comments#show"
      end
    end
  end

  resources :posts do
    member do
      post "like", to: "posts#like", as: :like
      post "unlike", to: "posts#unlike", as: :unlike
      # get ":slug", to: "posts#show", as: :show
      # get ":slug/edit", to: "posts#edit"
      # delete ":slug", to: "posts#destroy"
      # patch ":slug", to: "posts#update"
      # get ":slug/comments", to: "comments#index", as: :post_comments
      post "comments", to: "comments#create", as: :comments_create
      delete "comments/:id", to: "comments#destroy", as: :comment_destroy
      get "comments/:id/edit", to: "comments#edit", as: :comment_edit
      patch "comments/:id", to: "comments#update", as: :comment
      put "comments/:id", to: "comments#update", as: :comment_update
      post "comments/like", to: "comments#like", as: :comment_like
      post "comments/unlike", to: "comments#unlike", as: :comment_unlike
      # get ":slug/comments/:id", to: "comments#show"
    end
  end

  get "blog" => "pages#blog", as: :blog
  get "home" => "pages#home", as: :home

  scope :pages do
    get "blog" => "pages#blog"
    get "home" => "pages#home"
  end

  root 'pages#home'

  devise_for :user, path: "",
             path_names: { sign_in: "signin", sign_out: "signout", sign_up: "signup", password: "find_password" },
             controllers: {
                 :sessions => "users/sessions",
                 :registrations => "users/registrations",
                 :confirmations => "devise/confirmations",
                 :omniauth_callbacks => "users/omniauth_callbacks"
             }

  devise_scope :user do
    get "settings" => "users/registrations#edit", as: :settings
    get "find_password" => "devise/passwords#new", as: :find_password
    get "forgot_password" => "devise/passwords#new", as: :forgot_password
    get "resend" => "devise/confirmations#new", as: :resend
    post "auth/facebook" => "users/omniauth_callbacks#all"
    post "auth/linkedin" => "users/omniauth_callbacks#all"
    post "auth/google_oauth2" => "users/omniauth_callbacks#all"
    post "auth/twitter" => "users/omniauth_callbacks#all"
    post "auth/github" => "users/omniauth_callbacks#all"
  end

  # concern :sociable, Sociable

  # resources :posts do
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end
  # resources :courses do 
  #   resources :posts
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end













  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VotesHelper
  include CommentsHelper
  resourcify
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  acts_as_voteable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  before_action :set_comments, only: [:show, :edit, :like, :unlike, :destroy]
  before_filter :comment_params, only: [:create,:update]
  before_filter :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  def index
    @comments = Comment.all
    respond_to do |format|
      format.html {  }
      format.json { render json: @comments }
    end
  end

  def new
    parent = Comment.find_by_id(params[:parent_id])
    @obj = parent.commentable_type.constantize.find(parent.commentable_id)

    if signed_in?
    child_comment = parent.children.build_from(@obj, current_user.id, "")
    @comment = Comment.build_from(@obj, current_user.id, "")
    end

    respond_to do |format|
      format.js
    end
  end

  def create

    if params[:comment][:body].present?
      @comment.user_id = current_user.id
      @comment.created_at = Time.now
      @comment.updated_at = Time.now

      respond_to do |format|
        if @comment.save
          format.html { go_back }
          format.json { render json: @comment, status: :created }
          format.js
        else
          format.html { go_back, flash[:error] = "댓글작성에 실패했습니다." }
          format.json { render json: @comment.errors.full_messages, status: :unprocessable_entity }
          format.js
        end
      end

    else
      flash[:error] = "비어있는 댓글을 입력할 수 없습니다."
      go_back
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @comment }
    end
  end

  def edit
    thread_obj
    respond_to do |format|
      format.js
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { go_back }
        format.json { render json: @comment }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors.full_messages, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { go_back }
      format.json { head :no_content }
      format.js
    end
  end

  def like
    respond_to do |format|
      format.js
    end
  end

  def unlike
    respond_to do |format|
      format.js
    end
  end

  private
  def set_comments
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type, :title, :subject, :parent_id, :lft, :rgt)
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = t("unauthorized.#{controller_name}.#{exception.action}")
    go_back
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_obj_helper
    if params["controller"] == "comments" && params["action"] == "new"
      @comment.parent_id = params["parent_id"]
      @comment
    else
      @comment
    end
  end

  def comment_arg_helper
    if (params["controller"] == "posts" && params["action"] == "show") || (params["controller"] == "comments" && params["action"] == "new")
      @obj.id
    else
      @comment.id
    end
  end

  def comment_method_helper
    if params["controller"] == "comments" && params["action"] == "edit"
      :put
    else
      :post
    end
  end

  def comment_url_helper(param)
    if params["controller"] == "comments" && params["action"] == "edit"
      comment_update_post_path(param)
    else
      comments_create_post_path(param)
    end
  end

  def reply_indicator(parent_id)
    "<span class='reply_indicator'>#{name_mapper(User.find(Comment.find(parent_id).user_id))}</span>".html_safe || nil
  end

  def namer(parent_id)
    name_mapper(User.find(Comment.find(parent_id).user_id))
  end

  def thread_obj
    @obj = @comment.commentable_type.constantize.find(@comment.commentable_id)
  end
end

app/views/comments/_comment.html.erb
<li class="comment id_<%= comment.id %> clearfix">
    <div class="avatar_container">
      <%= image_tag "#{comment.user.avatar.default_url}", size: "40x40", class: "profile_image avatar" if !comment.user.sns_avatar? && comment.user.avatar.blank? %>
      <%= image_tag "#{comment.user.sns_avatar}", class: "profile_image avatar" if comment.user.sns_avatar? && comment.user.avatar.blank? %>
      <%= image_tag "#{comment.user.avatar.medium_avatar.url}", class: "profile_image avatar" if comment.user.avatar.present? %>
    </div>
    <div class="contents_container">
      <div class="contents_wrapper">
        <div class="clearfix">
        <div class="left">
          <h4 class="author"><%= name_mapper(comment.user) %><% if comment.vote_count > 0 %><strong class="vote_count">+<%= comment.vote_count %></strong><% end %></h4>
          <span class="time"><%= comment.updated_at.strftime("%Y.%m.%d %I:%M%P") %></span>
        </div>
        <div class="right">
          <ul class="control">
            <% if signed_in? %>
                <% if (can? :destroy, comment)%><li class="destroy"><%= link_to t("comments.comment_control.destroy"), comment_destroy_post_path(comment), method: :delete, data: { confirm: t("default.reask") }, remote: true %></li><% end %>
                <% if (can? :edit, comment)%><li class="edit"><%= link_to t("comments.comment_control.edit"), comment_edit_post_path(comment), remote: true %></li><% end %>
                <li class="reply"><%= link_to t("comments.comment_control.reply"), new_comment_path(comment), remote: true %></li>
                <% if current_user.voted_on?(comment) %><li class="vote"><%= link_to t("comments.comment_control.unlike"), comment_unlike_post_path(comment), method: :post, remote: true %></li><% end %>
                <% unless current_user.voted_on?(comment) %><li class="vote"><%= link_to t("comments.comment_control.like"), comment_like_post_path(comment), method: :post, remote: true %></li><% end %>
            <% end %>
          </ul>
        </div>
        </div>
        <p class="body"><%= comment.body %></p>
      </div>
    </div>
</li>

app/views/comments/_form.html.erb
<div id="comment_form_container" class="clearfix">
    <%= simple_form_for(comment_obj_helper, url: comment_url_helper(comment_arg_helper), remote: true, method: comment_method_helper) do |f| %>
      <%= f.hidden_field :parent_id %>
      <%= f.input :commentable_id, :as => :hidden, :value => comment_obj_helper.commentable_id %>
      <%= f.input :commentable_type, :as => :hidden, :value => comment_obj_helper.commentable_type %>
      <%= f.input :body, required: true, label: false, wrapper: false, input_html: { class: "content radius input_shadow autosize" } %>
      <%= f.submit t("default.save"), class: "submit button radius success tiny right" %>
    <% end %>
</div>

app/views/comments/create.js.erb
var response = $('<%= j render @comment %>').fadeIn();
<% if params["comment"]["parent_id"].present? %>
$('#comment_list_container ul li:first').before(response);
$('#comment_body').val('');
<% else %>
$('#comment_list_container ul li:first').before(response);
$('#comment_body').val('');
<% end %>

app/views/comments/destroy.js.erb
$('.comment.id_<%= @comment.id %>').fadeOut(300, function(){ $(this).remove(); });

app/views/comments/edit.js.erb
$(document).bind('DOMSubtreeModified',function(){
    $('.autosize').autosize();
});

var cancel = $('<div class="cancel"><%= link_to t("default.cancel"), "#", class: "button radius tiny alert" %></div>');
var edit_form = $('<%= j render("form") %>').fadeIn();
var contents_wrapper = $('.comment.id_<%= @comment.id %> .contents_wrapper');
var contents_container = $('.comment.id_<%= @comment.id %> .contents_container');

contents_container.prepend(edit_form);
$('.comment.id_<%= @comment.id %> #comment_form_container .submit').after(cancel);
contents_wrapper.css('display', 'none');

$('.comment.id_<%= @comment.id %> .cancel').click(function(evt){
    evt.preventDefault();
    $('.comment.id_<%= @comment.id %> #comment_form_container').remove();
    contents_wrapper.css('display', 'block');

});

app/views/comments/like.js.erb
<% if @comment.vote_count > 0 %>
<% current_user.vote_for(@comment) %>
$('.comment.id_<%= @comment.id %> .author .vote_count').replaceWith('<strong class="vote_count">+<%= @comment.vote_count %></strong>');
<% end %>

<% if @comment.vote_count == 0 %>
<% current_user.vote_for(@comment) %>
$('.comment.id_<%= @comment.id %> .author').append('<strong class="vote_count">+<%= @comment.vote_count %></strong>');
<% end %>

$('.comment.id_<%= @comment.id %> .control .vote').replaceWith('<li class="vote"><%= link_to t("comments.comment_control.unlike"), comment_unlike_post_path(@comment), method: :post, remote: true %></li>');

app/views/comments/new.js.erb
var form = $('<%= j render("form") %>').fadeIn();
$('#comment_form_container').replaceWith(form);
$('#comment_form_container .content').val('@<%= namer(@comment.parent_id) %> ');
$('#comment_form_container .content').focus();
var cancel = $('<div class="cancel"><%= link_to t("default.cancel"), "#", class: "button radius tiny alert right", style: "margin-right: 10px;" %></div>');
$('#comment_form_container .submit').after(cancel);

$('#comment_form_container .cancel').click(function(evt){
    evt.preventDefault();
    $(this).remove();
    $('#comment_form_container').replaceWith($('<%= j render("form") %>').fadeIn());
});

app/views/comments/unlike.js.erb
<% if @comment.vote_count > 1 %>
<% current_user.unvote_for(@comment) %>
$('.comment.id_<%= @comment.id %> .author .vote_count').replaceWith('<strong class="vote_count">+<%= @comment.vote_count %></strong>');
<% else %>
<% current_user.unvote_for(@comment) %>
$('.comment.id_<%= @comment.id %> .author .vote_count').remove();
<% end %>
$('.comment.id_<%= @comment.id %> .control .vote').replaceWith('<li class="vote"><%= link_to t("comments.comment_control.like"), comment_like_post_path(@comment), method: :post, remote: true %></li>');

app/views/comments/update.js.erb
var content = '<%= params["comment"]["body"] %>';

$('.comment.id_<%= @comment.id %> .contents_wrapper').css('display', 'block');
$('.comment.id_<%= @comment.id %> #comment_form_container').fadeOut(300, function(){ $(this).remove(); });
$('.comment.id_<%= @comment.id %> .cancel').fadeOut(300, function(){ $(this).remove(); });
$('.comment.id_<%= @comment.id %> .contents_wrapper .body').html(content);