config/routes.rb
Rails.application.routes.draw do

  resources :policies

  mount RedactorRails::Engine => '/redactor_rails'
  get "/comments/new/(:parent_id)", to: "comments#new", as: :new_comment
  post "/comments/new/(:parent_id)", to: "comments#create", as: :create_nested_comment

  resources :searches, except: [:index, :destroy, :edit, :update]

  resources :categories do
    resources :posts do
      member do
        post "like", to: "posts#like", as: :like
        post "unlike", to: "posts#unlike", as: :unlike
        # get ":slug", to: "posts#show", as: :show
        # get ":slug/edit", to: "posts#edit"
        # delete ":slug", to: "posts#destroy"
        # patch ":slug", to: "posts#update"
        # get ":slug/comments", to: "comments#index", as: :post_comments
        post "comments", to: "comments#create", as: :comments_create
        delete "comments/:id", to: "comments#destroy", as: :comment_destroy
        get "comments/:id/edit", to: "comments#edit", as: :comment_edit
        patch "comments/:id", to: "comments#update", as: :comment
        put "comments/:id", to: "comments#update", as: :comment_update
        post "comments/like", to: "comments#like", as: :comment_like
        post "comments/unlike", to: "comments#unlike", as: :comment_unlike
        # get ":slug/comments/:id", to: "comments#show"
      end
    end
  end

  resources :posts do
    member do
      post "like", to: "posts#like", as: :like
      post "unlike", to: "posts#unlike", as: :unlike
      # get ":slug", to: "posts#show", as: :show
      # get ":slug/edit", to: "posts#edit"
      # delete ":slug", to: "posts#destroy"
      # patch ":slug", to: "posts#update"
      # get ":slug/comments", to: "comments#index", as: :post_comments
      post "comments", to: "comments#create", as: :comments_create
      delete "comments/:id", to: "comments#destroy", as: :comment_destroy
      get "comments/:id/edit", to: "comments#edit", as: :comment_edit
      patch "comments/:id", to: "comments#update", as: :comment
      put "comments/:id", to: "comments#update", as: :comment_update
      post "comments/like", to: "comments#like", as: :comment_like
      post "comments/unlike", to: "comments#unlike", as: :comment_unlike
      # get ":slug/comments/:id", to: "comments#show"
    end
  end

  get "blog" => "pages#blog", as: :blog
  get "home" => "pages#home", as: :home

  scope :pages do
    get "blog" => "pages#blog"
    get "home" => "pages#home"
  end

  root 'pages#home'

  devise_for :user, path: "",
             path_names: { sign_in: "signin", sign_out: "signout", sign_up: "signup", password: "find_password" },
             controllers: {
                 :sessions => "users/sessions",
                 :registrations => "users/registrations",
                 :confirmations => "devise/confirmations",
                 :omniauth_callbacks => "users/omniauth_callbacks"
             }

  devise_scope :user do
    get "settings" => "users/registrations#edit", as: :settings
    get "find_password" => "devise/passwords#new", as: :find_password
    get "forgot_password" => "devise/passwords#new", as: :forgot_password
    get "resend" => "devise/confirmations#new", as: :resend
    post "auth/facebook" => "users/omniauth_callbacks#all"
    post "auth/linkedin" => "users/omniauth_callbacks#all"
    post "auth/google_oauth2" => "users/omniauth_callbacks#all"
    post "auth/twitter" => "users/omniauth_callbacks#all"
    post "auth/github" => "users/omniauth_callbacks#all"
  end

  # concern :sociable, Sociable

  # resources :posts do
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end
  # resources :courses do 
  #   resources :posts
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end













  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include VotesHelper
  include AttrSearchable
  attr_searchable :title, :body
  attr_searchable :comment => "comments.body"

  resourcify
  acts_as_ordered_taggable
  acts_as_ordered_taggable_on :tags
  acts_as_voteable
  acts_as_commentable

  acts_as_url(:slug, url_attribute: :slug)

  belongs_to :user
  has_many :views, as: :viewable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :category

  # has_many :limitations
  # has_many :limits, through: :limitations

  has_many :limits, as: :limitable

  scope :uncategorized, -> { posts.where(category_id: nil) }
  scope :recent, -> { order("posts.updated_at DESC") }
  scope :by_10, -> { limit(10) }

  validates :title, presence: false
  validates :body, presence: true
  validates :slug, presence: true
  validates :slug, uniqueness: true


  def to_param
    "#{slug}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::TextHelper # to use 'truncate' method

  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_filter :post_meta_info, only: [:show]
  before_filter :authenticate_user!, except: [:index, :show]

  load_and_authorize_resource

  def index
    if params[:search]
      # @posts = Post.search(params[:search])
      @posts = Post.where(title: "#{params[:search]}")
      respond_to do |format|
        format.html { redirect_to }
        # format.json { render json: @res }
      end
    else
      @posts = Post.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
      @category = Category.all
    end
  end

  def show
    @obj = @post
    @comment = Comment.build_from(@post, current_user.id, "") if signed_in?
    @comments = @post.comment_threads

    # Count Views
    if signed_in?
      @post.views.create(user_id: current_user.id, created_at: Time.now, updated_at: Time.now, ip: current_user.current_sign_in_ip) if (@post.views.where(user_id: current_user.id).blank?) && (@post.views.where(ip: current_user.current_sign_in_ip).blank?)
    else
      @post.views.create(user_id: @cached_guest_user.id, created_at: Time.now, updated_at: Time.now, ip: @cached_guest_user.current_sign_in_ip) if (@post.views.where(user_id: @cached_guest_user.id).blank?) && (@post.views.where(ip: @cached_guest_user.current_sign_in_ip).blank?)
    end

    if request.path != post_path(@post)
      redirect_to @post, status: :moved_permanently
    end
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def like
    if current_user.voted_on?(@post)
      flash[:warning] = "이미 좋아요를 했습니다."
    else
      current_user.vote_for(@post)
      go_back
    end
  end

  def unlike
    if current_user.voted_on?(@post)
      current_user.unvote_for(@post)
      go_back
    else
      flash[:warning] = "이미 좋아요를 취소했습니다."
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        limitations
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end


  private
  def set_post
    # @post = Post.find(params[:id])
    @post = Post.find_by_slug(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :tag_list, :category_id, :published, :slug, :limits => [], :limit_ids => [])
  end

  def post_meta_info
    @post_meta_published_time = @post.created_at
    @post_meta_updated_time = @post.updated_at
    @post_meta_category = "#{@post.category.name}" if @post.category.present?
    @post_meta_title = "[#{@post_meta_category}] " + "#{HTMLEntities.new.decode(@post.title)}" + "- seoyoochan.com"
    @post_meta_description = "#{truncate(Sanitize.clean(@post.body), length: 200)}".strip
    @post_meta_img = "#{Nokogiri::HTML(@post.body).css("img").map { |i| i["src"] }.first}" if @post.body.include? "<img src"
    @post_meta_tag = @post.tag_list.join(",") if @post.tag_list.present?
  end

  def limitations
    params[:post][:limit_ids].each do |e|
      Limit.create(name: e, limitable_type: "Post", limitable_id: @post.id) if @post && e.present?
    end
  end


  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = t("unauthorized.#{controller_name}.#{exception.action}")
    go_back
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_borderless.html.erb
<div id="borderless">
  <section class="header clearfix">
    <div class="title_container"><%= t("posts.total_html", total: "#{@posts.size}") %></div>
    <div class="control">
      <ul>
        <li><%= link_to t("posts.new"), new_post_path, class: "button info radius tiny" if can? :new, @posts %></li>
        <li><%= link_to t("default.back"), :back, class: "button secondary radius tiny" %></li>
      </ul>
    </div>
  </section>
  <ul class="posts">
    <% @posts.each do |post| %>
        <li class="clearfix">
          <nav class="general_info">
            <ul>
              <li class="user">
                <%= image_tag "#{post.user.avatar.default_url}", size: "27x27", class: "profile_image avatar" if !post.user.sns_avatar? && post.user.avatar.blank? %>
                <%= image_tag "#{post.user.sns_avatar}", class: "profile_image avatar" if post.user.sns_avatar? && post.user.avatar.blank? %>
                <%= image_tag "#{post.user.avatar.medium_avatar.url}", class: "profile_image avatar" if post.user.avatar.present? %>
              </li>
              <% if post.category.present? %><li class="categories"><%= link_to "<i class=\"fa fa-folder\"></i>#{post.category.name}".html_safe, post.category %></li><% end %>
              <li class="date"><i class="fa fa-calendar-o"></i><%= post.updated_at.strftime("%Y.%m.%d") %></li>
              <li class="time"><i class="fa fa-clock-o"></i><%= post.updated_at.strftime("%I:%M%P") %></li>
              <li class="comments"><i class="fa fa-comment"></i><%= post.comments.size %></li>
              <li class="likes"><i class="fa fa-heart"></i><%= post.vote_count %></li>
              <li class="views"><i class="fa fa-eye"></i><%= post.views.count %></li>
            </ul>
          </nav>
          <div class="post_info">
            <h3 class="title"><%= link_to "#{HTMLEntities.new.decode(summarize(post.title, 70))}", post_path(post) , class: "ease" %></h3>
            <div class="content">
              <%= truncate(Sanitize.fragment(post.body), :length => 200,  :separator => ' ') %>
            </div>
            <div class="tag_container">
              <ul>
                <% post.tags.each do |item| %>
                    <li><%= link_to "#{item.name}".html_safe, "#", class: "tag_item" %></li>
                <% end %>
              </ul>
            </div>
            <% if current_user == post.user %>
            <nav class="post_control">
              <ul>
                <li><%= link_to "<i class=\"fa fa-pencil-square-o\"></i>".html_safe, edit_post_path(post) if can? :edit, post %></li>
                <li><%= link_to "<i class=\"fa fa-times\"></i>".html_safe, post, method: :delete, data: { confirm: t("default.reask") } if can? :destroy, post %></li>
              </ul>
            </nav>
            <% end %>
          </div>
        </li>
    <% end %>
  </ul>
  <div class="pagination_container">
    <%= will_paginate @posts, renderer: FoundationPagination::Rails, previous_label: "<", next_label: ">", page_gap: "&hellip;" %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: { class: "post_form" }) do |f| %>
    <%= f.association :category, input_html: { class: "category input_shadow radius" }, label: false, required: false, wrapper: false, placeholder: t("categories.placeholder.select_category") %>
    <%= f.input :title, input_html: { class: "title input_shadow radius" }, autofocus: true, required: true, wrapper: false, label: false, placeholder: t("posts.placeholder.title") %>
    <%= f.input :slug, input_html: { class: "slug input_shadow radius" }, autofocus: false, required: true, wrapper: false, label: false, placeholder: t("posts.placeholder.slug") %>
    <%= f.input :body, input_html: { class: "content input_shadow radius redactor" }, autofocus: false, required: true, wrapper: false, label: false, placeholder: t("posts.placeholder.body") %>
    <%= f.input :tag_list, input_html: { class: "tags input_shadow radius" }, wrapper: false, label: false, placeholder: t("posts.placeholder.tag") %>

    <button data-dropdown="limitDrop" aria-controls="limitDrop" aria-expanded="false">Public</button>
    <div id="limitDrop" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
      <%= f.association :limits, collection: Limit.limits_group, as: :check_boxes, input_html: { class: "radius" }, wrapper: false, label: false %>
    </div>
    <%= f.submit t("default.save"), class: "submit button info radius small" %>
<% end %>

<%= link_to t("default.back"), @post, class: "button secondary tiny radius right back" %>

app/views/posts/edit.html.erb
<div id="post_edit" class="content_wrapper">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<style type="text/css">
    .waves-ripple {background-color: #55ACEE !important;}
</style>
<div id="blog" class="content_wrapper">
  <%= render "layouts/default_blog" %>
</div>

app/views/posts/new.html.erb
<div id="post_new" class="content_wrapper">
  <div class="row">
    <%= render "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<div id="post_read" class="content_wrapper">
  <div class="row">
    <section class="header clearfix">
      <div class="title_container"><%= t("posts.total_html", total: "#{Post.all.size}") %></div>
      <div class="control">
        <ul>
          <li><%= link_to t("posts.new"), new_post_path, class: "button info radius tiny" if can? :new, @post %></li>
          <li><%= link_to t("default.list"), blog_path, class: "button secondary radius tiny" %></li>
          <li><%= link_to t("default.back"), :back, class: "radius button secondary tiny" %></li>
        </ul>
      </div>
    </section>
    <nav class="general_info">
      <ul>
        <li class="user">
          <%= image_tag "#{@post.user.avatar.default_url}", size: "27x27", class: "profile_image avatar" if !@post.user.sns_avatar? && @post.user.avatar.blank? %>
          <%= image_tag "#{@post.user.sns_avatar}", class: "profile_image avatar" if @post.user.sns_avatar? && @post.user.avatar.blank? %>
          <%= image_tag "#{@post.user.avatar.medium_avatar.url}", class: "profile_image avatar" if @post.user.avatar.present? %>
        </li>
        <% if @post.category.present? %><li class="categories"><%= link_to "<i class=\"fa fa-folder\"></i>#{@post.category.name}".html_safe, @post.category %></li><% end %>
        <li class="time"><i class="fa fa-clock-o"></i><%= @post.updated_at.strftime("%Y.%m.%d at %I:%M%P") %></li>
        <li class="comment"><i class="fa fa-comment"></i><%= @post.comments.size %> <%= t("posts.comments") %></li>
        <li class="views"><i class="fa fa-eye"></i><%= @post.views.count %> <%= t("posts.views") %></li>
      </ul>
    </nav>
    <div class="divider"></div>
    <div class="title">
      <h3><%= HTMLEntities.new.decode(@post.title) %></h3>
    </div>
    <div class="divider"></div>
    <div class="content">
      <%= raw @post.body %>
    </div>
    <div class="bottom">
      <nav class="post_control">
        <ul>
            <% if current_user == @post.user %>
              <li><%= link_to "<i class=\"fa fa-pencil-square-o\"></i>".html_safe, edit_post_path(@post) if can? :edit, @post %></li>
              <li><%= link_to "<i class=\"fa fa-times\"></i>".html_safe, @post, method: :delete, data: { confirm: t("default.reask") } if can? :destroy, @post %></li>
            <% end %>
          <li>
            <% if signed_in? %>
                <%= link_to "<i class=\"fa fa-heart-o\"></i> #{@post.vote_count}".html_safe, unlike_post_path(@post.id), method: :post, class: "unlike ease" if current_user.voted_on?(@post) %>
                <%= link_to "<i class=\"fa fa-heart\"></i> #{@post.vote_count}".html_safe, like_post_path(@post.id), method: :post, class: "like ease" unless current_user.voted_on?(@post) %>
            <% else %>
                <%= link_to "<i class=\"fa fa-heart\"></i> #{@post.vote_count}".html_safe, new_user_session_path, class: "like ease"%>
            <% end %>
          </li>
        </ul>
      </nav>
    </div>
    <div class="tag_container">
      <ul>
        <li><%= link_to "<i class='fa fa-tag'></i>".html_safe, "#", class: "tag_icon" %></li>
        <% @post.tags.each do |item| %>
            <li><%= link_to "#{item.name}".html_safe, "#", class: "tag_item" %></li>
        <% end %>
      </ul>
    </div>

    <div id="social_button">
      <%= render_shareable :turbolinks => true, :facebook => {:turbolinks => false} %>
    </div>

    <div class="comments_container">

      <%= render "shared/login_suggestion" unless signed_in? %>
      <%= render partial: "comments/form" if signed_in? %>

      <div id="comment_list_container">
        <ul>
          <li></li>
          <%= render partial: "comments/comment", collection: @comments.order("updated_at DESC") %>
        </ul>
      </div>
    </div>
  </div>
</div>