config/routes.rb
Rails.application.routes.draw do

  resources :policies

  mount RedactorRails::Engine => '/redactor_rails'
  get "/comments/new/(:parent_id)", to: "comments#new", as: :new_comment
  post "/comments/new/(:parent_id)", to: "comments#create", as: :create_nested_comment

  resources :searches, except: [:index, :destroy, :edit, :update]

  resources :categories do
    resources :posts do
      member do
        post "like", to: "posts#like", as: :like
        post "unlike", to: "posts#unlike", as: :unlike
        # get ":slug", to: "posts#show", as: :show
        # get ":slug/edit", to: "posts#edit"
        # delete ":slug", to: "posts#destroy"
        # patch ":slug", to: "posts#update"
        # get ":slug/comments", to: "comments#index", as: :post_comments
        post "comments", to: "comments#create", as: :comments_create
        delete "comments/:id", to: "comments#destroy", as: :comment_destroy
        get "comments/:id/edit", to: "comments#edit", as: :comment_edit
        patch "comments/:id", to: "comments#update", as: :comment
        put "comments/:id", to: "comments#update", as: :comment_update
        post "comments/like", to: "comments#like", as: :comment_like
        post "comments/unlike", to: "comments#unlike", as: :comment_unlike
        # get ":slug/comments/:id", to: "comments#show"
      end
    end
  end

  resources :posts do
    member do
      post "like", to: "posts#like", as: :like
      post "unlike", to: "posts#unlike", as: :unlike
      # get ":slug", to: "posts#show", as: :show
      # get ":slug/edit", to: "posts#edit"
      # delete ":slug", to: "posts#destroy"
      # patch ":slug", to: "posts#update"
      # get ":slug/comments", to: "comments#index", as: :post_comments
      post "comments", to: "comments#create", as: :comments_create
      delete "comments/:id", to: "comments#destroy", as: :comment_destroy
      get "comments/:id/edit", to: "comments#edit", as: :comment_edit
      patch "comments/:id", to: "comments#update", as: :comment
      put "comments/:id", to: "comments#update", as: :comment_update
      post "comments/like", to: "comments#like", as: :comment_like
      post "comments/unlike", to: "comments#unlike", as: :comment_unlike
      # get ":slug/comments/:id", to: "comments#show"
    end
  end

  get "blog" => "pages#blog", as: :blog
  get "home" => "pages#home", as: :home

  scope :pages do
    get "blog" => "pages#blog"
    get "home" => "pages#home"
  end

  root 'pages#home'

  devise_for :user, path: "",
             path_names: { sign_in: "signin", sign_out: "signout", sign_up: "signup", password: "find_password" },
             controllers: {
                 :sessions => "users/sessions",
                 :registrations => "users/registrations",
                 :confirmations => "devise/confirmations",
                 :omniauth_callbacks => "users/omniauth_callbacks"
             }

  devise_scope :user do
    get "settings" => "users/registrations#edit", as: :settings
    get "find_password" => "devise/passwords#new", as: :find_password
    get "forgot_password" => "devise/passwords#new", as: :forgot_password
    get "resend" => "devise/confirmations#new", as: :resend
    post "auth/facebook" => "users/omniauth_callbacks#all"
    post "auth/linkedin" => "users/omniauth_callbacks#all"
    post "auth/google_oauth2" => "users/omniauth_callbacks#all"
    post "auth/twitter" => "users/omniauth_callbacks#all"
    post "auth/github" => "users/omniauth_callbacks#all"
  end

  # concern :sociable, Sociable

  # resources :posts do
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end
  # resources :courses do 
  #   resources :posts
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end













  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
  resourcify
  belongs_to :user
  has_many :posts, dependent: :nullify

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:user_id, :name)
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = t("unauthorized.#{controller_name}.#{exception.action}")
    go_back
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: { class: "category_form" } ) do |f| %>
    <div class="name_container">
      <%= f.input :name, input_html: { class: "name input_shadow radius" }, autofocus: true, required: true, wrapper: false, label: false, placeholder: t("categories.placeholder.name")  %>
    </div>

    <div>
      <%= f.submit t("default.save"), class: "submit button info tiny radius" %>
    </div>
<% end %>

<%= link_to t("default.list"), categories_path, class: "button secondary tiny radius right" %>

app/views/categories/edit.html.erb
<div id="category_edit" class="content_wrapper">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<div id="category_index" class="content_wrapper">
  <div class="row">
    <section class="header clearfix">
      <div class="title_container"><%= t("categories.total_html", total: "#{@categories.size}") %></div>
      <div class="control">
        <ul>
          <li><%= link_to t("categories.new"), new_category_path, class: "button info radius tiny"if can? :new, @category  %></li>
          <li><%= link_to t("default.list"), categories_path, class: "button secondary tiny radius" if can? :index, @category %></li>
          <li><%= link_to t("default.back"), :back, class: "button secondary radius tiny" %></li>
        </ul>
      </div>
    </section>
    <section class="footer">
      <ul class="list">
        <% @categories.each do |category| %>
            <li>
              <span class="title"><%= link_to "• #{category.name} <small>(#{category.posts.size})</small>".html_safe, category, class: "ease" %></span>
              <% if can? :edit, Category %>
              <div class="control">
                <ul>
                  <li><%= link_to t("default.edit"), edit_category_path(category), class: "button info radius tiny" if can? :edit, category %></li>
                  <li><%= link_to t("default.destroy"), category, method: :delete, data: { confirm: t("default.reask") }, class: "button info radius tiny"  if can? :destroy, category %></li>
                </ul>
              </div>
              <% end %>
            </li>
        <% end %>
      </ul>
    </section>
  </div>
</div>

app/views/categories/new.html.erb
<div id="category_new" class="content_wrapper">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/show.html.erb
<div id="category_show" class="content_wrapper">
  <div class="row">
    <section class="header clearfix">
      <div class="title_container"><%= t("categories.related_post_html", name: "#{@category.name}",total: "#{@category.posts.size}") %></div>
      <div class="control">
        <ul>
          <li><%= link_to t("categories.new"), new_category_path, class: "button info radius tiny" if can? :new, @category %></li>
          <li><%= link_to t("default.edit"), edit_category_path(@category), class: "btn_edit button info tiny radius" if can? :edit, @category %></li>
          <li><%= link_to t("default.list"), categories_path, class: "button secondary tiny radius" if can? :index, @category %></li>
          <li><%= link_to t("default.back"), :back, class: "button secondary radius tiny" %></li>
        </ul>
      </div>
    </section>

    <section class="footer">
      <ul>
        <% @category.posts.each do |post| %>
           <li class="clearfix"><%= link_to "<span class='title'>• #{HTMLEntities.new.decode(summarize(post.title, 85))}</span><span class='date'><i class=\"fa fa-clock-o\"></i>#{post.created_at.strftime("%Y.%m.%d at %I:%M%P")}</span>".html_safe, post, class: "ease" %></li>
        <% end %>
      </ul>
    </section>
  </div>
</div>