config/routes.rb
Rails.application.routes.draw do

  resources :policies

  mount RedactorRails::Engine => '/redactor_rails'
  get "/comments/new/(:parent_id)", to: "comments#new", as: :new_comment
  post "/comments/new/(:parent_id)", to: "comments#create", as: :create_nested_comment

  resources :searches, except: [:index, :destroy, :edit, :update]

  resources :categories do
    resources :posts do
      member do
        post "like", to: "posts#like", as: :like
        post "unlike", to: "posts#unlike", as: :unlike
        # get ":slug", to: "posts#show", as: :show
        # get ":slug/edit", to: "posts#edit"
        # delete ":slug", to: "posts#destroy"
        # patch ":slug", to: "posts#update"
        # get ":slug/comments", to: "comments#index", as: :post_comments
        post "comments", to: "comments#create", as: :comments_create
        delete "comments/:id", to: "comments#destroy", as: :comment_destroy
        get "comments/:id/edit", to: "comments#edit", as: :comment_edit
        patch "comments/:id", to: "comments#update", as: :comment
        put "comments/:id", to: "comments#update", as: :comment_update
        post "comments/like", to: "comments#like", as: :comment_like
        post "comments/unlike", to: "comments#unlike", as: :comment_unlike
        # get ":slug/comments/:id", to: "comments#show"
      end
    end
  end

  resources :posts do
    member do
      post "like", to: "posts#like", as: :like
      post "unlike", to: "posts#unlike", as: :unlike
      # get ":slug", to: "posts#show", as: :show
      # get ":slug/edit", to: "posts#edit"
      # delete ":slug", to: "posts#destroy"
      # patch ":slug", to: "posts#update"
      # get ":slug/comments", to: "comments#index", as: :post_comments
      post "comments", to: "comments#create", as: :comments_create
      delete "comments/:id", to: "comments#destroy", as: :comment_destroy
      get "comments/:id/edit", to: "comments#edit", as: :comment_edit
      patch "comments/:id", to: "comments#update", as: :comment
      put "comments/:id", to: "comments#update", as: :comment_update
      post "comments/like", to: "comments#like", as: :comment_like
      post "comments/unlike", to: "comments#unlike", as: :comment_unlike
      # get ":slug/comments/:id", to: "comments#show"
    end
  end

  get "blog" => "pages#blog", as: :blog
  get "home" => "pages#home", as: :home

  scope :pages do
    get "blog" => "pages#blog"
    get "home" => "pages#home"
  end

  root 'pages#home'

  devise_for :user, path: "",
             path_names: { sign_in: "signin", sign_out: "signout", sign_up: "signup", password: "find_password" },
             controllers: {
                 :sessions => "users/sessions",
                 :registrations => "users/registrations",
                 :confirmations => "devise/confirmations",
                 :omniauth_callbacks => "users/omniauth_callbacks"
             }

  devise_scope :user do
    get "settings" => "users/registrations#edit", as: :settings
    get "find_password" => "devise/passwords#new", as: :find_password
    get "forgot_password" => "devise/passwords#new", as: :forgot_password
    get "resend" => "devise/confirmations#new", as: :resend
    post "auth/facebook" => "users/omniauth_callbacks#all"
    post "auth/linkedin" => "users/omniauth_callbacks#all"
    post "auth/google_oauth2" => "users/omniauth_callbacks#all"
    post "auth/twitter" => "users/omniauth_callbacks#all"
    post "auth/github" => "users/omniauth_callbacks#all"
  end

  # concern :sociable, Sociable

  # resources :posts do
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end
  # resources :courses do 
  #   resources :posts
  #   concerns: :sociable, only: [:create, :update, :destroy]
  # end













  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_default_blog.html.erb
<div class="row">
  <div class="large-10 columns">
    <% if Post.any? %>
        <%= render "posts/borderless" %>
    <% else %>
        <div style="width:220px;margin: 0 auto;text-align: center;">
          <h5>현재 등록된 글이 없습니다.</h5>
          <%= link_to "글작성", new_post_path, class: "button small info radius" if can? :edit, Post %>
        </div>
    <% end %>
  </div>
  <div class="large-2 columns">
    <div class="widget_container">
      <h3 class="title_container"><strong class="title"><%= link_to t("current_path.category"), categories_url %></strong></h3>
      <nav class="category_container">
        <ul>
          <% @category.each do |category| %>
              <li><%= link_to "• #{category.name} <small>(#{category.posts.size})</small>".html_safe, category, class: "ease" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="footer">
	<div class="row">
		<div class="large-12 columns">

		</div>
	</div>
 </footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="row">
  <h2 class="logo"><%= link_to t("browser_title.default"), root_path, class: "logo_name animsition" %><span class="current_path"><%= current_path %></span></h2>
  <%= render "layouts/menu" %>
  </div>
</header>

app/views/layouts/_menu.html.erb
<div class="menu_container">
  <div class="menu-wrap">
    <nav class="menu-top">
      <div class="menu-top_wrapper">
        <% if signed_in? %>
        <div class="profile right">
          <%= image_tag "#{current_user.avatar.default_url}", size: "80x80",class: "avatar" if !current_user.sns_avatar? && current_user.avatar.blank? %>
          <%= image_tag "#{current_user.sns_avatar}", class: "avatar" if current_user.sns_avatar? && current_user.avatar.blank? %>
          <%= image_tag "#{current_user.avatar.small_avatar.url}", class: "avatar" if current_user.avatar.present? %>
        <span class="name"><%= name_mapper(current_user) %></span></div>
        <div class="icon-list right">
          <%= link_to "<i class=\"fa fa-fw fa-star-o\"></i>".html_safe, "#" if signed_in? %>
          <%= link_to "<i class=\"fa fa-fw fa-bell-o\"></i>".html_safe, "#" if signed_in? %>
          <%= link_to "<i class=\"fa fa-fw fa-comment-o\"></i>".html_safe, "#" if signed_in? %>
          <%= link_to "<i class=\"fa fa-cog\"></i>".html_safe, settings_path if signed_in? %>
        </div>
        <% end %>
      </div>
    </nav>
    <nav class="menu-side">
      <ul>
        <li>
        <div class="search_container">
          <div class="search_style-2">
            <span class="icon"><i class="fa fa-search"></i></span>
            <%= simple_form_for @search_object do |f| %>
                <%= f.input :keywords, required: false, autofocus: false, placeholder: "Search...", label: false, wrapper: false, input_html: { class: "search_bar" } %>
                <%= f.submit "", wrapper: false, class: "search_submit" %>
            <% end %>
          </div>
        </div>
        </li>
        <li><%= link_to t("menu.top.about"), root_path %></li>
        <li><%= link_to t("menu.top.work"), "#" %></li>
        <li><%= link_to t("menu.top.blog"), blog_path %></li>
        <% if signed_in? %>
            <li><%= link_to t("menu.top.signout"), destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to t("menu.top.signin"), user_session_path %></li>
            <li><%= link_to t("menu.top.signup"), new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <button class="menu-button" id="open-button"><i class="fa fa-bars"></i></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s %>" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="<%= t("meta_tags.home.title") %>">
    <meta name="Description" content="<%= t("meta_tags.home.description") %>>">
    <meta name="Keywords" content="Ruby,Ruby on Rails,Javascript,jQuery,Tutorials,CSS,HTML,Tips,Workarounds,루비온레일스,자바스크립트,튜토리얼,Resources">
    <title><%= content_for?(:title) ? yield(:title) : t("browser_title.default") %></title>
    <%= csrf_meta_tags %>
    <%= render "shared/social_meta_tags" %>
    <link href='//fonts.googleapis.com/earlyaccess/nanumgothic.css' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application" %>
    <script type="text/javascript">
        (function($) {
            $(document).ready(function() {
                $("#flash").delay(5000).fadeOut(300);

                var csrf_token = $('meta[name=csrf-token]').attr('content');
                var csrf_param = $('meta[name=csrf-param]').attr('content');
                var params;
                if (csrf_param !== undefined && csrf_token !== undefined) {
                    params = csrf_param + "=" + encodeURIComponent(csrf_token);
                }
                $('.redactor').redactor(
                        { "imageUpload":"/redactor_rails/pictures?" + params,
                            "imageGetJson":"/redactor_rails/pictures",
                            "fileUpload":"/redactor_rails/documents?" + params,
                            "fileGetJson":"/redactor_rails/documents",
                            "path":"/assets/redactor-rails",
                            "lang": "<%= I18n.locale.to_s %>",
                            "css":""}
                );
            });
        })(jQuery);
    </script>
    <style type="text/css">
      <%= header_line %>
    </style>
  </head>
  <body>
  <%= render "shared/flash" %>
  <%= render "layouts/header" %>
  <div id="scrollTopTarget" class="content_menu_responder">
    <% unless params["action"] == "home" %>
    <div id="scrollTop">
        <%= link_to "<i class=\"fa fa-arrow-up\"></i>".html_safe, "#scrollTopTarget", class: "ease" %>
    </div>
    <% end %>
    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-55121874-1', 'auto');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
  </script>
  </body>
</html>